# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  # Individual variables
  - name: firstName
    value: 'Gaurav'
  - name: lastName
    value: 'Sharma'
  - name: fullName
    value: '$(firstName) $(lastName)'
  - group: TerraformVars
  - group: testvariables



steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo hello world
    ls 
    ls -la
    ls terra*
  displayName: Commands

- script: |
    echo $(Build.BuildId)
    echo $(Build.BuildNumber)
    echo $(System.TeamProject)
    echo $(Agent.OS)
  displayName: Checking some system variables

- script: |
    echo $(TF_VAR_client_id)
    echo $(TF_VAR_client_secret)
    echo $(TF_VAR_subscription_id)
    echo $(TF_VAR_tenant_id)
    echo $(firstName)
    echo $(lastName)
    echo $(fullName)
    echo now executing for testvariables
    echo $(Bankpassword)
    echo $(BankUser)
    echo $(Surname)
    python --version
    python print("Hello world")
  displayName: Checking group variables in Pipeline

